### ISSUE TITLE
Build for Python 3.9

### ISSUE THREAD

**Issue by stanmart** [conda-forge/vega-feedstock#50]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Even though there does not seem to be any dependencies holding back this feedstock, there is nor build for Python 3.9 yet. AFAIK normally the regro-cf-autotick-bot would create a pull request with the updated feedstock automatically, but it did not happen here for some reason. I've tried rerendering the feedstock with conda-build 3.20.5, conda-smithy 3.8.5, and conda-forge-pinning 2020.12.09.12.04.26, but no `****_python3.9.____cpython.yaml` files were created in the .ci_support folder. It would be great if someone could find out what's the issue here.

**Comment by ocefpaf** [comment]
Poetry is missing. We need to fix https://github.com/conda-forge/poetry-feedstock/pull/37 to get this one going.

**Comment by ocefpaf** [comment]
Just fixed all the missing dependencies for poetry and merge it. A PR for this one should be issued soon by the bot.
